RESPONSE_SUCCESS = "Success"
RESPONSE_ERROR = "Error"
RESPONSE_FAILED = "Failed"

MULTIPLE_ROWS_RETURNED = "Multiple Rows Returned"
AUTHORIZATION_HEADER_DOES_NOT_EXISTS = "Authorization Header Does Not Exists"
AUTHORIZATION_HEADER_DOES_NOT_CONFIGURED_PROPERLY = "Authorization Header Does Not Configured Properly"
AUTHORIZATION_HEADER_DOES_NOT_MATCH = "Authorization Header Does Not Match"
AUTHORIZATION_PARSE_ERROR = "Authorization Parse Error"
INVALID_SIGNATURE = "Invalid Signature"
EXPIRED_SIGNATURE = "Expired Signature"
USER_IDENTIFIER_NOT_FOUND_IN_JWT = "User identifier not found in JWT"
USER_NOT_FOUND = "User not found"
USER_DOES_NOT_MATCH = "User Does Not Match"

USER_ALREADY_EXISTS = "User Already Exists"
USER_DOES_NOT_EXISTS = "User Does Not Exists"
PASSWORD_DOES_NOT_MATCH = "Password Does Not Match"
AUTHENTICATION_FAILED = "Authentication Failed"

OBJECTS_NOT_FOUND = "Objects Not Found"